# Generated by Django 3.0.8 on 2020-07-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_workerinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attackinfo',
        ),
        migrations.DeleteModel(
            name='Workerinfo',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='api_token',
        ),
    ]
