# Generated by Django 3.0.8 on 2020-07-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200721_1429'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userinfo',
            new_name='Logininfo',
        ),
    ]
