# Generated by Django 3.0.8 on 2020-07-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logininfo',
            new_name='Victiminfo',
        ),
    ]
