# Generated by Django 3.0.8 on 2020-07-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200723_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='r_url',
            field=models.CharField(default='https://www.google.com', max_length=100),
        ),
    ]
